<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\Branch;
use App\Models\Company;
use App\Models\Role;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserProdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Oscar',
                'last_name' => 'Lopez',
                'second_last_name' => 'Rodriguez',
                'email' => 'admin@alianzaelectrica.com',
                'password' => Hash::make('T1C0MP3T3NC&APP$'),
                'active' => true,
                'role_id' => Role::ADMIN,
                'area_id' => Area::TECNOLOGIAS_INFORMACION,
                'company_id' => Company::ALIANZA_ELECTRICA,
                'branch_id' => Branch::ATIZAPAN,
            ],
            [
                'id' => '2',
                'name' => 'Roberto',
                'last_name' => 'Blasi',
                'second_last_name' => 'Heredia',
                'email' => 'roberto.blasi@alianzaelectrica.com',
                'password' => '$2y$12$8D5z.cG3JrRprgRFcnC4g.OxMXjiAe2yGJJnhApxAubEWjCwW34j6',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::RECURSOS_HUMANOS,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '3',
                'name' => 'Julio Giovani',
                'last_name' => 'Parra',
                'second_last_name' => 'Galvan',
                'email' => 'julio.parra@fgelectrical.com',
                'password' => '$2y$12$kBZ7CVN5LHfEHZ1/jLAHaeHu6nVHJUdYFvcKSraDI7eny9vdjzgDG',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::RECURSOS_HUMANOS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '4',
                'name' => 'Marina Martha',
                'last_name' => 'Paredon',
                'second_last_name' => 'Uribe',
                'email' => 'marina.paredon@alianzaelectrica.com',
                'password' => '$2y$12$/os7XYdR4CJH49UYSrzsAe47rJFw98P1ahe1ACAgmDDS3PMVOL55i',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::RECURSOS_HUMANOS,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '5',
                'name' => 'Emily Andrea',
                'last_name' => 'Avila',
                'second_last_name' => 'Lopez',
                'email' => 'emily.avila@tablerosyarrancadores.com',
                'password' => '$2y$12$oNuh8mlTcHJ/UqRV0i6JHeMP8WmZUNDiSvkjItZvY46CVDbr2.VK6',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '6',
                'name' => 'YOLANDA CECILIA',
                'last_name' => 'LEON',
                'second_last_name' => 'PAREDES',
                'email' => 'cecilia.leon@fgelectrical.com',
                'password' => '$2y$12$AhHaiREy5/vOtAJPLyp6TulRk.bZgdSRgXhPtorWGJSijareMqF3m',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '7',
                'name' => 'MARIA LUZ',
                'last_name' => 'MORALES',
                'second_last_name' => 'GALVAN',
                'email' => 'lucy.morales@fgelectical.com',
                'password' => '$2y$12$ic169jsMJj7A2hQE0CtRheGTi3/SHc3dCSN/LMw2yv549dA5uK3ly',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '8',
                'name' => 'ERNESTINA',
                'last_name' => 'VILLELA',
                'second_last_name' => 'TRENADO',
                'email' => 'ernestina.villela@fgelectrical.com',
                'password' => '$2y$12$myZ374b0Jzvzlbw7d.wbwuOM5J7p9f6eGlLgdbamBBZElne0u8WZi',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '9',
                'name' => 'GUSTAVO ARMANDO',
                'last_name' => 'ALVA',
                'second_last_name' => 'AVILA',
                'email' => 'gustavo.alva@fgelectrical.com',
                'password' => '$2y$12$nvq6L0hD.BLTAI5f0zj9WukxF6HtJIPuKZjeuAeBZa7QdoWxdzeIO',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::SEGURIDAD_HIGIENE,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '10',
                'name' => 'Liliana',
                'last_name' => 'Flores',
                'second_last_name' => 'Monroy',
                'email' => 'liliana.flores@fgelectrical.com',
                'password' => '$2y$12$SeFxibJ5g.vvGwGk8Czsje5N5tvLMDtzP/OAyrro3qhkJ3/vjOIOK',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::RECURSOS_HUMANOS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '12',
                'name' => 'Teresa',
                'last_name' => 'Marquez',
                'second_last_name' => 'Pineda',
                'email' => 'teresa.marquez@fgelectrical.com',
                'password' => '$2y$12$MuM9o1URlHKifKytLSN9nO4JOzM66MiLTuLph/frjWI3O02YRwsRW',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::AUDITORIA_INTERNA,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '13',
                'name' => 'José Roberto',
                'last_name' => 'Flores',
                'second_last_name' => 'Marroquin',
                'email' => 'jose.flores@alianzaelectrica.com',
                'password' => '$2y$12$BzhVBVeSdZOYLZo1jgOYuugt88zvu3iNppdpJDJY1TeEID/plfIiy',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::LOGISTICA,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '14',
                'name' => 'Elias',
                'last_name' => 'Garcia',
                'second_last_name' => 'Vidal',
                'email' => 'elias.garcia@fgelectrical.com',
                'password' => '$2y$12$LQpjPrx/gd/e9ZLm1bdwoe7igprF5wvb8InPHwL/IK2iqSOPj5Y0i',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::INGENIERIA,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '15',
                'name' => 'Luis Enrique',
                'last_name' => 'Munguia',
                'second_last_name' => 'Corona',
                'email' => 'luis.munguia@tablerosyarrancadores.com',
                'password' => '$2y$12$o6KW2rUeSDYl0FdW/VpP4.crkPwTXjzKkzcQBhk7cmQsACgmcDhOC',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '16',
                'name' => 'Felix Enrique',
                'last_name' => 'Peña',
                'second_last_name' => 'Reyes',
                'email' => 'felix.pena@tablerosyarrancadores.com',
                'password' => '$2y$12$yOygxu0KtKBrvfR9NEUzleMjhrFYnDxqtPWHPBU5rAAW8NEQtfLv.',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '17',
                'name' => 'Jorge',
                'last_name' => 'Ruiz',
                'second_last_name' => 'Santiago',
                'email' => 'jorge.ruiz@fgelectrical.com',
                'password' => '$2y$12$5I9U0/stOxw1L2ytqhOKVeC8IDuenw.pkoE0ATfZSi2Ml/yZiP0gq',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::CALIDAD,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '18',
                'name' => 'FRANCISCO',
                'last_name' => 'MANZANARES',
                'second_last_name' => 'LOPEZ',
                'email' => 'francisco.manzanares@valmact.com',
                'password' => '$2y$12$R4PJTSjpC.jWcfzQJ5quQuKyvS2Q8ACOhje2d5PTs.44prRGy44O2',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::PRODUCCION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '19',
                'name' => 'Javier Ignacio',
                'last_name' => 'Avalos',
                'second_last_name' => 'Colin',
                'email' => 'javier.avalos@fgelectrical.com',
                'password' => '$2y$12$vK3Th4GihwNdlJmChVK1tueUj6//Pc3fixiD20crbdrT5zSFs40yG',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '20',
                'name' => 'Sandra Denisse',
                'last_name' => 'Gomez',
                'second_last_name' => 'Ramirez',
                'email' => 'sandra.gomez@fgelectrical.com',
                'password' => '$2y$12$cyxLUj6rIyj67NatCNct9.LeejJvHnE6Awe1Ja4okWh1B4bTf97PW',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::PRODUCCION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '21',
                'name' => 'norma',
                'last_name' => 'cruz',
                'second_last_name' => 'reyes',
                'email' => 'supervisor@fgelectrical.com',
                'password' => '$2y$12$R6UrwgW8ZuOAHLXyqCjuEugZWGTH38cext4HsjeEiUvsqBYdom0wS',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::CALIDAD,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '22',
                'name' => 'LUIS',
                'last_name' => 'RAMIREZ',
                'second_last_name' => 'SERRANO',
                'email' => 'luis.ramirez@fgelectrical.com',
                'password' => '$2y$12$xgikva1MS0Sm/dKr7DAD0eIBccqwUmXazH/THXRG6KVfFaxPR1lhe',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '23',
                'name' => 'KAREN SARAI',
                'last_name' => 'Gomez',
                'second_last_name' => 'Luna',
                'email' => 'karen.luna@fgelectrical.com',
                'password' => '$2y$12$YetZ96nyDKRZhYDOg1sC2uF2cc3pL7u.e4gQxlPQAYXRxLfVA/PYi',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::COMPRAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '24',
                'name' => 'LETICIA',
                'last_name' => 'OBISPO',
                'second_last_name' => 'ACOSTA',
                'email' => 'leticia.obispo@alianzaelectrica.com',
                'password' => '$2y$12$V8PfJAwEQLXdybX2Ketj0eRHjCyCHkJoQHoTU.gJsS2j7DQTSd/6K',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '25',
                'name' => 'Tania Vanessa',
                'last_name' => 'Monterrubio',
                'second_last_name' => 'Jurad',
                'email' => 'tania.monterrubio@fgelectrical.com',
                'password' => '$2y$12$9K6OjC1qmRcd9mV.Rc2xQOGYiDGnRW/6uhp1mRcV5yFc7kO26cnH2',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::COMPRAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '26',
                'name' => 'Nancy Claudia',
                'last_name' => 'Hernandez',
                'second_last_name' => 'Segura',
                'email' => 'nancy.hernandez@fgelectrical.com',
                'password' => '$2y$12$bSulkIDlz9alIMgBAjucl.Xk9CbFNwisd7uv.8NOCBdzp1/U.NIW2',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '27',
                'name' => 'Rafael',
                'last_name' => 'Maldonado',
                'second_last_name' => 'Garcia',
                'email' => 'rafael.maldonado@alianzaelectrica.com',
                'password' => '$2y$12$Ca9V9Iz1QFqBcTW2/kfl.eMHCnTxF//0uPfD7Ft2nu4RufNLGI.eW',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::INGENIERIA,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '28',
                'name' => 'CARLOS ALBERTO',
                'last_name' => 'GONZALEZ',
                'second_last_name' => 'CERVANTES',
                'email' => 'carlos.gonzalez@fgelectrical.com',
                'password' => '$2y$12$05.Pv4z7pT0HubT9N4gO5euq6ayzMZVruF/h/bFzuba/2XnjuGnY6',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '29',
                'name' => 'JOSE  ANGEL',
                'last_name' => 'GALVAN',
                'second_last_name' => 'ISAIZ',
                'email' => 'angel.galvan@tablerosyarrancadores.com',
                'password' => '$2y$12$WgfoSa4KqT407U5GtEG4OerEHqWtRqfgBLcLt0GdfkiqiVjqIC53e',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '30',
                'name' => 'Dalia Janeeth',
                'last_name' => 'Bermudez',
                'second_last_name' => 'Morales',
                'email' => 'janeeth.bermudez@fgelectrical.com',
                'password' => '$2y$12$WTxhIFn0c6Ya7WNCy1nwe.98CTtcmmLP/ofk0F7RL6mvQ3XaS29QK',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '31',
                'name' => 'Alfredo',
                'last_name' => 'Arzate',
                'second_last_name' => 'Hernandez',
                'email' => 'alfredo.arzate@fgelectrical.com',
                'password' => '$2y$12$F9.IN9WCijdCeHLfM62pK.oY.RARc8NMkG9.GanlETWLlD2pXIk9y',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '32',
                'name' => 'Antonio',
                'last_name' => 'Zamora',
                'second_last_name' => 'Flores',
                'email' => 'antonio.zamora@fgelectrical.com',
                'password' => '$2y$12$NpWjjwWT4zgxTZd36MbbqOGgXQsjiW8ENXzOdk5ayQtL7sxqQA7Ky',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '33',
                'name' => 'MONICA EDITH',
                'last_name' => 'Velador',
                'second_last_name' => 'Llamas',
                'email' => 'monica.velador@fgelectrical.com',
                'password' => '$2y$12$w/GsiYQxJxvqWuP2mlRAc.7QUGOGM7Q0Y5rRqtB6jT8Z8KlZhYBLW',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '40',
                'name' => 'ivonne',
                'last_name' => 'mora',
                'second_last_name' => 'aguilar',
                'email' => 'ivonne.mora@tablerosyarrancadores.com',
                'password' => '$2y$12$UXNwD4HX1U6thbTB2Bf6xO5/eHNa/K5v1CmYfplRmhSImgRgc.vha',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::INGENIERIA,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '41',
                'name' => 'CONY JOCELIN',
                'last_name' => 'BONILLA',
                'second_last_name' => 'OLIVERA',
                'email' => 'jocelin.bonilla@tablerosyarrancadores.com',
                'password' => '$2y$12$5YjVRoIRPiVre6/ZIr5ZieoVnmtLtMl0ImH8B7bzR2Na4VbBSUnUq',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '42',
                'name' => 'ALBERTO',
                'last_name' => 'GOMEZ',
                'second_last_name' => 'PULIDO',
                'email' => 'alberto.gomez@fgelectrical.com',
                'password' => '$2y$12$704vwQTutOOm9zParfCZp.GrYWMXD6qnkksiAHwZAM09IhYcTHC4m',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '43',
                'name' => 'Ricardo',
                'last_name' => 'Peralta',
                'second_last_name' => 'Torres',
                'email' => 'ricardo.peralta@tablerosyarrancadores.com',
                'password' => '$2y$12$X7ffZYee./B8yzV00m3DgeAHWnAyj6IG8Z.4EuRa0lWMdIsljh4uu',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '44',
                'name' => 'ILSE MONSERRAT',
                'last_name' => 'VARGAS',
                'second_last_name' => 'TLAZALO',
                'email' => 'ilse.vargas@fgelectrical.com',
                'password' => '$2y$12$JAdP90uQi0ioYmsBEoIv3OPRUP0vLWD4EcyFBRhxOlQE53hk5jBnS',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::SEGURIDAD_HIGIENE,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '45',
                'name' => 'DULCE CAROLINA',
                'last_name' => 'ROMERO',
                'second_last_name' => 'PADILLA',
                'email' => 'dulce.romero@fgelectrical.com',
                'password' => '$2y$12$lmGBzhcwJ8ahnepkhRUFGuuYZ0CVbhRTbbCiKYqdnqqRuQk7hEAAu',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '46',
                'name' => 'YENY',
                'last_name' => 'JIMENEZ',
                'second_last_name' => 'HERNANDEZ',
                'email' => 'yeny.jimenez@fgelectrical.com',
                'password' => '$2y$12$DIcZlKLSAwhkmMpKYQz06uH7JTPlBYRJITm849.J5EjADuUTnQIe6',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '47',
                'name' => 'José Augusto',
                'last_name' => 'Alvarez',
                'second_last_name' => 'Navarro',
                'email' => 'augusto.alvarez@tablerosyarrancadores.com',
                'password' => '$2y$12$wFwnF.sy./Rztl3zJdfWCug3RjMgAzMLCYDWDfiBc1YgIhjpfPlG2',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '48',
                'name' => 'María del Pilar',
                'last_name' => 'Lazcano',
                'second_last_name' => 'Alvarez',
                'email' => 'pilar.lazcano@alianzaelectrica.com',
                'password' => '$2y$12$mmtbsjK0YF24oot.UnKisOK2v/itNdLh8bMYxerp6QxIY4DuSQyM.',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '50',
                'name' => 'Daniel Mauricio',
                'last_name' => 'Guzman',
                'second_last_name' => 'Armenta',
                'email' => 'daniel.guzman@alianzaelectrica.com',
                'password' => '$2y$12$jQf1V3F5lMUCfEzZWOQWPuZ0..Dfwr2XNmkfTAnIwuOfqgKfQz29m',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '51',
                'name' => 'Johana Patricia',
                'last_name' => 'Santos',
                'second_last_name' => 'Bautista',
                'email' => 'servicioaclientes@tablerosyarrancadores.com',
                'password' => '$2y$12$qSWoov.eqM0AYKX7/4/wmecV4Z28DXuX/7r28X.PGbh9EKOjuznv2',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '52',
                'name' => 'Juan Antonio',
                'last_name' => 'Ortiz',
                'second_last_name' => 'Jimenez',
                'email' => 'juan.ortiz@fgelectrical.com',
                'password' => '$2y$12$eyn14XKZ7jE8hLEbBVoONOE050xKdcHAtr2EQvLV5Qu0te3fhTAwi',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '53',
                'name' => 'Jonathan',
                'last_name' => 'Perez',
                'second_last_name' => 'Perez',
                'email' => 'jonathan.perez@fgelectrical.com',
                'password' => '$2y$12$CmNXTYOHS/1BdddUiP3ox.s4MkvB84Sz9.hlc6DsKBt7g4a8ar0fi',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '54',
                'name' => 'Arturo',
                'last_name' => 'Chavarria',
                'second_last_name' => 'Resendiz',
                'email' => 'arturo.chavarria@alianzaelectrica.com',
                'password' => '$2y$12$Fsbu5uptTiWQcdDSefJQIuKuHSTvnMZnFbZNyHiVIXU2G5mJhfn2m',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '56',
                'name' => 'Gonzalo',
                'last_name' => 'Mata',
                'second_last_name' => 'Camacho',
                'email' => 'gonzalo.matac@fgelectrical.com',
                'password' => '$2y$12$U0Z9oY4YmaU/ALaPQD3nSO2BbozUkpTtuXarNmDSndQGpLgwtbGxO',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '64',
                'name' => 'Fernando',
                'last_name' => 'Mata',
                'second_last_name' => 'Camacho',
                'email' => 'fernando.mata@alianzaelectrica.com',
                'password' => '$2y$12$wDUaILolhhuJV5.C/6octOMHi6YrLETgno6qlajhibBS06.sGzrB2',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '65',
                'name' => 'Gloria Adriana',
                'last_name' => 'Carrillo',
                'second_last_name' => 'Carbajal',
                'email' => 'gadriana.carrillo@alianzaelectrica.com',
                'password' => '$2y$12$w5P7wCzLpi4/96zDdooXzOsIDlxFLqFeTrlgavlbMRY.6uYikUW6W',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::LOGISTICA,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '67',
                'name' => 'Francisco',
                'last_name' => 'Manzanares',
                'second_last_name' => 'Lopez',
                'email' => 'francisco.manzanares@alianzaelectrica.com',
                'password' => '$2y$12$21i6ldA9hU/HHhdFN/GnEeX8BAdR13dV0wXWv8q0zGnTE7aEs6YEG',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::PRODUCCION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '68',
                'name' => 'Ricardo',
                'last_name' => 'Aguilar',
                'second_last_name' => 'Ortiz',
                'email' => 'ricardo.aguilar@fgelectrical.com',
                'password' => '$2y$12$gMXbJdlRtNannJh9Y4zV5uHcPE.13FJrzOADfK5mXWMLR3HS8Y2ye',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::PRODUCCION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '69',
                'name' => 'Miriam',
                'last_name' => 'Santiago',
                'second_last_name' => 'Gonzalez',
                'email' => 'claudia.gonzalez@alianzaelectrica.com',
                'password' => '$2y$12$Q3lTithhmS4t8.sdkHqqbOThLa3qFYvCL7yUdqgJNXWMfXVUMaezy',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::PRODUCCION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '71',
                'name' => 'Luis Manuel',
                'last_name' => 'Lili',
                'second_last_name' => 'Olivares',
                'email' => 'supervisor.soldadura@fgelectrical.com',
                'password' => '$2y$12$ilcCbZYj6oqCTWPoSyIZ0.8LOcg7Q6tYVRNIl2RiPgFdV3sA6Q.Lq',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::PRODUCCION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '72',
                'name' => 'Alejandro Eliseo',
                'last_name' => 'Bernardino',
                'second_last_name' => 'Hernandez',
                'email' => 'almacen.mp@fgelectrical.com',
                'password' => '$2y$12$ox5r6JeaWwB/M9kRKuFJY.mUs8QrApbrpjXoqO0it8mNff3CgbbbW',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '73',
                'name' => 'Rafael',
                'last_name' => 'Solis',
                'second_last_name' => 'Chavez',
                'email' => 'rafael.solis@fgelectrical.com',
                'password' => '$2y$12$c2SQssIrU6INZUtLDIozSev1h4WKbO3W/2l9yv9fLTe5CIJAHcKCS',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '74',
                'name' => 'Alfonso',
                'last_name' => 'Ortuño',
                'second_last_name' => 'González',
                'email' => 'alfonso.ortuno@fgelectrical.com',
                'password' => '$2y$12$e0ecmXHTsu3bF7QysCZc7OpC.rT.xzRkMq4mfbvnVJRoujpB.cBBy',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::CALIDAD,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '76',
                'name' => 'Beatriz',
                'last_name' => 'Vazquez',
                'second_last_name' => 'Velazquez',
                'email' => 'beatriz.vazquez@alianzaelectrica.com',
                'password' => '$2y$12$uRZkLWBt2zAHthcWpOpm.OK.8hFyObs/g.Jjo55zXkSSI7xLm00Ny',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '78',
                'name' => 'Nancy',
                'last_name' => 'Villanueva',
                'second_last_name' => 'Loera',
                'email' => 'nancy.villanueva@fgelectrical.com',
                'password' => '$2y$12$oDssbJbqBrCWmMpyrhLPm.aM7Q0EDB0kvzQouLh3ChVlycsADstMe',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::LOGISTICA,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '79',
                'name' => 'Antonio',
                'last_name' => 'Hernandez',
                'second_last_name' => 'Martinez',
                'email' => 'antonio.hernandez@fgelectrical.com',
                'password' => '$2y$12$zzhATlw9LXvp6LRshfudu.iQZdXI0R5rgMYQZser2hQxKEy53B.Iq',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::RECURSOS_HUMANOS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '81',
                'name' => 'ESTEFANY',
                'last_name' => 'MALDONADO',
                'second_last_name' => 'CORIA',
                'email' => 'diana.maldonado@fgelectrical.com',
                'password' => '$2y$12$9NpkiAgGju9/6uc2j6RSVuCE1Moe47yvvMmB23eMiuiBYy1PP6XrW',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::CALIDAD,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '83',
                'name' => 'Rodrigo Emanuel',
                'last_name' => 'Mendez',
                'second_last_name' => 'AQUINO',
                'email' => 'emanuel.mendez@fgelectrical.com',
                'password' => '$2y$12$RlOV4fMop2R2rBfHQb4eDu1Oam8JalY3SLNHP3ym68UVZMERvUHlu',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::CALIDAD,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '84',
                'name' => 'Erick Ivan',
                'last_name' => 'Limones',
                'second_last_name' => 'Morales',
                'email' => 'erick.limones@alianzaelectrica.com',
                'password' => '$2y$12$btMd5C/kkXf.Osq54dKHhepFBcLtKtIVADgVywClC7.flKR47wk/a',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '85',
                'name' => 'JUAN ANTONIO',
                'last_name' => 'CERVANTES',
                'second_last_name' => 'PEREZ',
                'email' => 'juan.cervantes@alianzaelectrica.com',
                'password' => '$2y$12$/ZzPzYHlaEPI/lnwzxZgie7S2M7FXu5XUKOnnlXlrOgP79qWyEmQW',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::LOGISTICA,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '86',
                'name' => 'Gonzalo',
                'last_name' => 'Mata',
                'second_last_name' => 'Ruiz',
                'email' => 'gonzalo.mata@alianzaelectrica.com',
                'password' => '$2y$12$2iO28sCHa7W4/qd6bONvO.1OZbRUGH31STAh5RraXpWXkM4csZ0Za',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::PRODUCCION,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '87',
                'name' => 'Miguel',
                'last_name' => 'Gomez',
                'second_last_name' => 'Artega',
                'email' => 'marteaga1974@hotmail.com',
                'password' => '$2y$12$btU2nMZKrancb1ZbGVNg.OzN3MEqPM1DAt6Y.9opKgHHXHvjhAydS',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '88',
                'name' => 'Alexa',
                'last_name' => 'Aguilar',
                'second_last_name' => 'Barrera',
                'email' => 'alexa.aguilar@tablerosyarrancadores.com',
                'password' => '$2y$12$j.T94ZEj4zU9g96Qlh5Iced5PD3v45RwWlwUB7bReQK3PyOzJoW5y',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '89',
                'name' => 'CARLOS DANIEL',
                'last_name' => 'ZACARIAS',
                'second_last_name' => 'PINACHO',
                'email' => 'carlos.zacarias@fgelectrical.com',
                'password' => '$2y$12$fxW0y2MN7d2j45pwu2drHuDugpqSTaIc5YHTJoUd3C2Ld./mkzrUG',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '93',
                'name' => 'MARIA LUZ',
                'last_name' => 'MORALES',
                'second_last_name' => 'GALVAN',
                'email' => 'lucy.morales@valmact.com',
                'password' => '$2y$12$zhldgyaLzgQQbzTYudEU3OIyz1wX5Hj/oh7eMH/XcSVfi70GTOyOq',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '94',
                'name' => 'MARCOS AURELIANO',
                'last_name' => 'LARA',
                'second_last_name' => 'RODRIGUEZ',
                'email' => 'marcos.lara@alianzaelectrica.com',
                'password' => '$2y$12$DoTitslG1AqA9scMNrck/OkowQmtNdETfNMRQOAbathl90hFzO7Oe',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '95',
                'name' => 'Lizeth',
                'last_name' => 'Avila',
                'second_last_name' => 'Rocha',
                'email' => 'lizeth.avila@alianzaelectrica.com',
                'password' => '$2y$12$a317i/iygQeEYqD8OLTT1uwehgRYeQMR7ChW7qZ.W8GqY8EKa160q',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '104',
                'name' => 'Eder Omar',
                'last_name' => 'Rodriguez',
                'second_last_name' => 'Leyva',
                'email' => 'equipo.mantenimiento@alianzaelectrica.com',
                'password' => '$2y$12$wZ3/dU.prYwwXG6rXv0Bu.xbzEOU7IctDJgdXFvYd5THvNTTz0Fca',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MANTENIMIENTO,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '106',
                'name' => 'SEBASTIAN',
                'last_name' => 'RAMIREZ',
                'second_last_name' => 'CANO',
                'email' => 'sofiaelena09@gmail.com',
                'password' => '$2y$12$6FibLNUSXbavgF.5zG3p2eFr.okhQTPlpM5.wUyxx03N2x9lBZdTS',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '107',
                'name' => 'DEMIAN ANDRES',
                'last_name' => 'ALVAREZ',
                'second_last_name' => 'ANGULO',
                'email' => 'aaademian1@gmail.com',
                'password' => '$2y$12$Ck2StQ5sjoDBZN.ulvOHYOdt1SZPY/FG7B7sVRpp0.sbXpo9GSiVW',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '108',
                'name' => 'Alexa',
                'last_name' => 'Aguilar',
                'second_last_name' => 'Barrera',
                'email' => 'alexa.aguilar@alianzaelectrica.com',
                'password' => '$2y$12$1v2n2wYkym7PuVKeJ4F0jub48NFf4VzB2UiA8Dhs6H3WmfjPrJDT.',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '109',
                'name' => 'Paola',
                'last_name' => 'Ortiz',
                'second_last_name' => 'Quiroz',
                'email' => 'paola.ortiz@alianzaelectrica.com',
                'password' => '$2y$12$Wcj7zwaLAxNiNu6T5rJV8OExOUZ7PU6fgUcdJQu8QCyunDm9id/Yq',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '110',
                'name' => 'Rocio',
                'last_name' => 'HERNANDEZ',
                'second_last_name' => 'VARGAS',
                'email' => 'rocio.hernandez@alianzaelectrica.com',
                'password' => '$2y$12$Jj9qTAmw5ji16JXC7u8lW.uUrRcBQBsLIBMyXhr0VnmeEm4FAXtCO',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ATENCION_CLIENTES,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '111',
                'name' => 'REY DAVID',
                'last_name' => 'VILLALOBOS',
                'second_last_name' => 'CABALLERO',
                'email' => 'reydavidvillalobos56@gmail.com',
                'password' => '$2y$12$n3FiSnJLTZu4CKdOFJy3meENzNiNY9VLwb0dNtXUHYT.Bvcfhmpsy',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ALMACEN,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '112',
                'name' => 'Joel',
                'last_name' => 'Cruz',
                'second_last_name' => 'Jaime',
                'email' => 'joel.cruz@fgelectrical.com',
                'password' => '$2y$12$7s7ewiFraXCT2ba0qV7wDemuLCeDFaUHyd24cKzze0DOL/EF2taKi',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::INGENIERIA,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '113',
                'name' => 'Luis Angel',
                'last_name' => 'Vazquez',
                'second_last_name' => 'Perez',
                'email' => 'angeloles40@gmail.com',
                'password' => '$2y$12$/X1Sft/aSI9vYfg4BAnY4.QaRxMtIa1yZ.00/RlY3zu8wWfira6l2',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::INGENIERIA,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '114',
                'name' => 'Jose Isabel',
                'last_name' => 'Contreras',
                'second_last_name' => 'Lira',
                'email' => 'vicm4n07@gmail.com',
                'password' => '$2y$12$CW.SW3simXqiQpFkT1Gu8ek7fMbQMlnu38WLfXtS.9vKjEyyxsGnO',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::INGENIERIA,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '115',
                'name' => 'pompeyo',
                'last_name' => 'islas',
                'second_last_name' => 'calleja',
                'email' => 'pompeyoislas1@gmail.com',
                'password' => '$2y$12$ORlwV3a2SNaS4EbsmKuSz.oS0e30KgwrUJpiPAu8elZwerAFGQJRq',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::INGENIERIA,
                'company_id' => Company::MANOFACTURING,
            ],
            [
                'id' => '116',
                'name' => 'juan carlos',
                'last_name' => 'mendoza',
                'second_last_name' => 'manzanares',
                'email' => 'jcarlosmendoza1970@gmail.com',
                'password' => '$2y$12$8NbaXJHztFWmcjKrqxvPbOvJY7RJivPGVHTcpaTci.ZaGqu.CUsNe',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MANTENIMIENTO,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '117',
                'name' => 'miguel angel',
                'last_name' => 'merino',
                'second_last_name' => 'bello',
                'email' => 'escalybur7@hotmail.com',
                'password' => '$2y$12$Bb.yDOz6wL/dBUp2vq9mBOVnXTLVtJj4XB8vk3qxD7y0cUOBvdydO',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MANTENIMIENTO,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '118',
                'name' => 'Iselt Adriana',
                'last_name' => 'Olvera',
                'second_last_name' => 'Galicia',
                'email' => 'iselt.olvera@alianzaelectrica.com',
                'password' => '$2y$12$g/Boxa/SE93.ssQVXJk.peAC2JvwH0/2K3XRLfurJ3ZyRB0JkLLDO',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::RECURSOS_HUMANOS,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '122',
                'name' => 'VIOLETA',
                'last_name' => 'DELGADILLO',
                'second_last_name' => 'FLORES',
                'email' => 'violeta.delgadillo@fgelectrical.com',
                'password' => '$2y$12$zoYR32PbIVOrYHsRkyxCy.I0.wHkscuhgdLk9agJZ4PD11p49vMxa',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '123',
                'name' => 'Israel',
                'last_name' => 'Cocco',
                'second_last_name' => 'Castro',
                'email' => 'israel.cocco@fgelectrical.com',
                'password' => '$2y$12$X7yFGauKqOY3DTgIdbWYGeSRjP3XtvylAaKpkinI6GS7Gw3A0.p5O',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '124',
                'name' => 'Erick',
                'last_name' => 'Lecuona',
                'second_last_name' => 'Castañón',
                'email' => 'erick.lecuona@alianzaelectrica.com',
                'password' => '$2y$12$qQlSgJ00wsMi/My8TyxAC.RRaeVGRZWjAZIbSQdzAOABW7OSPlOnO',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MERCADOTECNIA,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '125',
                'name' => 'HECTOR',
                'last_name' => 'MATA',
                'second_last_name' => 'RUIZ',
                'email' => 'hector.mata@fgelectrical.com',
                'password' => '$2y$12$YZkbOMo.7EzgYslO4614Xesxkui6qBTQudBkhJGAUA8.cNokS9fuK',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::FG_ELECTRICAL,
            ],
            [
                'id' => '126',
                'name' => 'Juan Carlos',
                'last_name' => 'Morales',
                'second_last_name' => 'Godinez',
                'email' => 'juan.morales@alianzaelectrica.com',
                'password' => '$2y$12$MlwCHw9drpTA61UuZVKAdeI3dbScdiuRHjvlBG8m0Lmu8AWasqZCi',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::MERCADOTECNIA,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '127',
                'name' => 'Daniela Abigail',
                'last_name' => 'Perez',
                'second_last_name' => 'Perez',
                'email' => 'daniela.perez@alianzaelectrica.com',
                'password' => '$2y$12$BgV92.eNnjG0Or4Xxc1j1uqL1PfH4JbJK3ofQfBbsFvrMc47LTZ0y',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MERCADOTECNIA,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '128',
                'name' => 'Fernanda',
                'last_name' => 'Lozano',
                'second_last_name' => 'Flores',
                'email' => 'fernanda.lozano@alianzaelectrica.com',
                'password' => '$2y$12$wAryCgMUfPDKSoGsK5xMDu1e8kszm0WFKjj/VPyX2lL1o7G.0oeXe',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MERCADOTECNIA,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '129',
                'name' => 'Berenice Anahi',
                'last_name' => 'MALDONADO',
                'second_last_name' => 'Cuellar',
                'email' => 'bere.2664@gmail.com',
                'password' => '$2y$12$VNaWc91UFiHE6NSCoZnJ0edmE6GevAgn8clZhg5UbFnBaP9INPDzK',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MERCADOTECNIA,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '130',
                'name' => 'Gerardo',
                'last_name' => 'Garrido',
                'second_last_name' => 'Hernandez',
                'email' => 'gerardo.garrido@alianzaelectrica.com',
                'password' => '$2y$12$6tVRhX.gDR4Lf1pilckEUunPYnldq071wgUT0dQqPRH98kDZjdEIC',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::MERCADOTECNIA,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '131',
                'name' => 'Iliana Del Socorro',
                'last_name' => 'Garcia',
                'second_last_name' => 'Mata',
                'email' => 'iliana.garcia@alianzaelectrica.com',
                'password' => '$2y$12$6ae.BzBdG5pSoqPES9TmAO9Mv9Dy0rYiD0YJ1byUQy1oJUBtLhJ3W',
                'active' => true,
                'role_id' => Role::MANAGERS,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '132',
                'name' => 'LUIS ROBERTO',
                'last_name' => 'NUÑEZ',
                'second_last_name' => 'FAJARDO',
                'email' => 'l.roberto@tablerosyarrancadores.com',
                'password' => '$2y$12$lR1kfMfWYESBuBvLcydbAeUkzus92jRHDk9DMtE.GMNyBbOUd0aiO',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::VENTAS,
                'company_id' => Company::TABLEROS_ARRANCADORES,
            ],
            [
                'id' => '133',
                'name' => 'TERESA',
                'last_name' => 'ROMERO',
                'second_last_name' => 'CAZARES',
                'email' => 'teresa.romero@alianzaelectrica.com',
                'password' => '$2y$12$jHBilJeSq4p8LNQOtU9K.u2A5rnLmRo2JRQMiH2K5bick7lAmZZru',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '134',
                'name' => 'katyana',
                'last_name' => 'Ortuño',
                'second_last_name' => 'Pantaleon',
                'email' => 'katyana.ortuno@alianzaelectrica.com',
                'password' => '$2y$12$5IPCwUCpbo21k39WIFvq5OPxPiT/JgDx2WvMBwsmw/AW0Xcj.7WhG',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => '135',
                'name' => 'JOSE DOMINGO',
                'last_name' => 'OLIVEROS',
                'second_last_name' => 'RUIZ',
                'email' => 'domingo.oliveros@alianzaelectrica.com',
                'password' => '$2y$12$BFIQn02SjesdFNv5x1IoaObMVkhv60U99eJQ3BBfxLA90KqgWdMtO',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
            [
                'id' => 136,
                'name' => 'ARLET',
                'last_name' => 'BONILLA',
                'second_last_name' => 'CONTRERAS',
                'email' => 'arlet.bonilla@alianzaelectrica.com',
                'password' => '$2y$12$9nLi.tJSb9GRptgdf28vauPQyZI7pmV1Hmv2T9dC/AK0q.L9rqYCa',
                'active' => true,
                'role_id' => Role::EMPLOYEE,
                'area_id' => Area::ADMINISTRACION,
                'company_id' => Company::ALIANZA_ELECTRICA,
            ],
        ]);
    }
}
